name: Build Expo App with Bun

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    environment: Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Install EAS CLI
        run: bun add --dev eas-cli

      - name: Build Android APK Locally
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          npx eas build --platform android --local --non-interactive --output=./app.apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: app-apk
          path: ./app.apk
